### ISSUE TITLE
Cannot complete setup via "codewars setup --token <api access token>"

### ISSUE THREAD

**Issue by erampono** [shime/codewars#13]
I am on a macbook running Mojave 10.14.4. 
I have run `npm install -g codewars-client`. However, when I then run: 
`codewars setup --token <my token went here>` I get:
```
fs.js:134
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:134:9)
    at Object.writeFile (fs.js:1180:14)
    at /usr/local/lib/node_modules/codewars-client/index.js:76:8
    at /usr/local/lib/node_modules/codewars-client/node_modules/mkdirp/index.js:48:26
    at FSReqCallback.oncomplete (fs.js:160:5)
```
I have wrapped my token as a string `"12345"` and also as blank text `12345`.
Apologies as I am new to raising issues on GitHub and this issue relates to a previous issue that has already been closed - I don't know whether to re-open an old issue or make a new issue as I don't know the protocol. 

Thanks! Love the idea of this cli - it means I will get to upskill in my coding and zsh/neovim usage all at once!

**Comment by shime** [comment]
Thank you for reporting, I've just published a new version with the fix. Let me know if you experience any other issues.

**Comment by el-iot** [comment]
it works!! thank you :)
